sudo: required
services:
  - docker

before_install:
  - docker build -t adityasanil/capstone-test -f ./client/Dockerfile.dev ./client

script:
  - docker run adityasanil/capstone-test npm test -- --coverage --watchAll=false

after_success:
  - docker build -t adityasanil/capstone-client ./client
  - docker build -t adityasanil/capstone-nginx ./nginx
  - docker build --build-arg PORT=5000 -t adityasanil/capstone-api  ./api
  - docker build -t adityasanil/capstone-api2 ./api2

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push adityasanil/capstone-client
  - docker push adityasanil/capstone-nginx
  - docker push adityasanil/capstone-api
  - docker push adityasanil/capstone-api2

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: udacity-capstone
  env: UdacityCapstone-env
  bucket_name: elasticbeanstalk-us-east-1-688502995527
  bucket_path: udacity-capstone-env
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
