version: "3"
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
  api2:
    build:
      dockerfile: Dockerfile.dev
      context: ./back2
    volumes:
      - /usr/app/node_modules
      - ./back2:/usr/app
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./back
    volumes:
      - /usr/app/node_modules
      - ./back:/usr/app
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /usr/app/node_modules
      - ./client:/usr/app
