version: "3"
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "8080:8080"
  api2:
    build:
      dockerfile: Dockerfile.dev
      context: ./api2
    volumes:
      - /usr/app/node_modules
      - ./api2:/usr/app
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    volumes:
      - /usr/app/node_modules
      - ./api:/usr/app
  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /usr/app/node_modules
      - ./client:/usr/app
