apiVersion: v1
kind: Service
metadata:
  labels:
    service: server-api
  name: server-api
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    service: server-api
